- name: Check if docker is installed
  stat: path={{ docker_service }}
  register: install_result

- name: Install docker
  shell: curl -fsSL https://get.docker.com/ | sh
  when: not install_result.stat.exists

- name: Allow Docker Remote API
  lineinfile:
    path: /lib/systemd/system/docker.service
    regexp: 'ExecStart=/usr/bin/dockerd -H fd://'
    line: 'ExecStart=/usr/bin/dockerd -H fd:// -H tcp://0.0.0.0:4243 -H tcp://0.0.0.0:2376 --tlsverify --tlscacert=/root/ca.pem --tlscert=/root/server-cert.pem --tlskey=/root/server-key.pem'
    backup: no

- name: Copy seed.sh script to the main manager
  copy:
    src: seed.sh
    dest: /root/seed.sh

- name: Generate the certificates
  become: yes
  become_user: root
  shell: >
    /bin/bash /root/seed.sh
  args:
    chdir: /root

- name: Download the client certificates
  fetch:
    src: /root/{{ item }}
    dest: ../certificates/{{ item }}/
  with_items:
    - cert.pem
    - key.pem
    - ca.pem
  flat: yes

- name: Restart systemd daemon and stop docker if it is already started
  systemd:
    state: restarted
    daemon_reload: yes
    name: docker
    enabled: yes

- name: Check the docker status
  shell: >
    curl -k https://{{ vagrant_primary_docker_ip }}:4243/info --cert /root/cert.pem --key /root/key.pem --cacert /root/ca.pem | python -m json.tool
  register: docker_status

- set_fact:
    docker_info: "{{ docker_status.stdout | from_json }}"
