---

- name: Install transport-https
  apt: name={{ item }} state=latest
  with_items:  
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common
  tags:
    - packages

- name: Update
  shell: apt-get clean && apt-get update

- name: Install required packages
  apt: name={{ item }} state=latest
  with_items:
    - netcat-traditional
    - nmap
    - htop
    - sysstat
    - python-pip
    - bind9
    - jq
    - netcat-openbsd
  tags:
    - packages
   
#- name: install docker python dependencies
#  pip: name:{{ item.name }} version={{ item.version | default(omit) }}
#  with_items:
#    - { name: pyyaml }
#    - { name: docker-py, version: 1.9.0 }
#  tags:
#    - packages
