- name: Check if docker is installed
  stat: path={{ docker_service }}
  register: install_result

- name: Install docker
  shell: curl -fsSL https://get.docker.com/ | sh
  when: not install_result.stat.exists

- name: Allow Docker Remote API
  lineinfile:
    path: /lib/systemd/system/docker.service
    regexp: 'ExecStart=/usr/bin/dockerd -H fd://'
    line: 'ExecStart=/usr/bin/dockerd -H fd:// -H tcp://0.0.0.0:4243'
    backup: no

- name: Restart systemd daemon and start docker
  systemd:
    state: restarted
    daemon_reload: yes
    name: docker
    enabled: yes

- name: Check the docker status
  shell: >
    curl http://{{ vagrant_primary_docker_ip }}:4243/info | python -m json.tool
  register: docker_status

- set_fact:
    docker_info: "{{ docker_status.stdout | from_json }}"
